language: python
python:
  - "3.6"

# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "pip install python-coveralls"
# command to run tests
cache: false
before_script:
  - sudo -u postgres bash -c "psql -c \"CREATE USER db_admin WITH PASSWORD '';\""
  - psql -c 'create database bucketlist_dev;' -U postgres
  - psql -c 'create database bucketlist_test;' -U postgres
  - "rm -rf migrations/"
  - "./manage.py db init"
  - "./manage.py db migrate"
  - "./manage.py db upgrade"

script:
  - "nosetests --with-coverage"
  - "coveralls"

services:
  - postgresql

after_script:
 - coveralls
