language: python
python:
  - "3.6"

# command to install dependencies
install:
  - "pip install -r requirements.txt"
# command to run tests
before_script:
  - psql -c 'create database bucketlist_test;' -U postgres
  - psql -c 'createuser -P -s -e db_admin;' -U postgres
  - "./manage.py db migrate"
  - "./manage.py db upgrade"

script: "./manage.py test"

services:
  - postgresql
