"""empty message

Revision ID: 13879de4a781
Revises: 2855f039b13a
Create Date: 2017-05-07 01:41:47.434577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13879de4a781'
down_revision = '2855f039b13a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('bucketitem_name_key', 'bucketitem', type_='unique')
    op.drop_constraint('bucketlist_name_key', 'bucketlist', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('bucketlist_name_key', 'bucketlist', ['name'])
    op.create_unique_constraint('bucketitem_name_key', 'bucketitem', ['name'])
    # ### end Alembic commands ###
