"""empty message

Revision ID: 54d48e3fa2df
Revises: 69ef9f1e99f4
Create Date: 2017-04-26 19:29:39.865932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54d48e3fa2df'
down_revision = '69ef9f1e99f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bucketitem', sa.Column('description', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bucketitem', 'description')
    # ### end Alembic commands ###
